apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-grafana
  namespace: grafana-loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data-wh
  namespace: grafana-loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: grafana-loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
